--libext svh

-v/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_assert_standard_macros.svh
-v/Users/javad/dev/eval/opentitan/extra_files/prim_buf.sv 
-v/Users/javad/dev/eval/opentitan/extra_files/prim_pkg.sv 
-v/Users/javad/dev/eval/opentitan/extra_files/prim_flop.sv 
prim_assert_yosys_macros.svh

+incdir+/Users/javad/dev/eval/opentitan/extra_files
+incdir+/Users/javad/dev/eval/opentitan/hw/ip/aes/model
+incdir+/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl

+incdir+/Users/javad/dev/eval/opentitan/
+define+SIMULATION
+define+DUT_HIER=tb.dut
+define+EN_MASKING=1
+define+SBOX_IMPL=aes_pkg::SBoxImplDom

/Users/javad/dev/eval/opentitan/extra_files/prim_flop_2sync.sv
/Users/javad/dev/eval/opentitan/hw/top_earlgrey/rtl/top_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/entropy_src/rtl/entropy_src_pkg.sv
/Users/javad/dev/eval/opentitan/extra_files//prim_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_cipher_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_generic/rtl/prim_generic_and2.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_generic/rtl/prim_generic_buf.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_generic/rtl/prim_generic_flop.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_generic/rtl/prim_generic_xnor2.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_generic/rtl/prim_generic_xor2.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_pad_wrapper_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_22_16_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_22_16_enc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_28_22_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_28_22_enc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_39_32_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_39_32_enc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_64_57_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_64_57_enc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_72_64_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_72_64_enc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_hamming_22_16_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_hamming_22_16_enc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_hamming_39_32_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_hamming_39_32_enc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_hamming_72_64_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_hamming_72_64_enc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_hamming_76_68_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_hamming_76_68_enc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_inv_22_16_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_inv_22_16_enc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_inv_28_22_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_inv_28_22_enc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_inv_64_57_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_inv_64_57_enc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_inv_72_64_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_inv_72_64_enc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_22_16_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_22_16_enc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_39_32_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_39_32_enc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_72_64_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_72_64_enc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_76_68_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_76_68_enc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_sha2_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_xilinx/rtl/prim_xilinx_and2.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_xilinx/rtl/prim_xilinx_buf.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_xilinx/rtl/prim_xilinx_clock_mux2.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_xilinx/rtl/prim_xilinx_flop.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_xilinx/rtl/prim_xilinx_flop_en.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_xilinx_ultrascale/rtl/prim_xilinx_ultrascale_and2.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_xilinx_ultrascale/rtl/prim_xilinx_ultrascale_buf.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_xilinx_ultrascale/rtl/prim_xilinx_ultrascale_clock_inv.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_xilinx_ultrascale/rtl/prim_xilinx_ultrascale_clock_mux2.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_xilinx_ultrascale/rtl/prim_xilinx_ultrascale_flop.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_xilinx_ultrascale/rtl/prim_xilinx_ultrascale_flop_en.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_xilinx_ultrascale/rtl/prim_xilinx_ultrascale_xor2.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_xilinx/rtl/prim_xilinx_xor2.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_arbiter_fixed.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_arbiter_ppc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_arbiter_tree.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_arbiter_tree_dup.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_cdc_rand_delay.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_subst_perm.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_present.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_prince.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_count_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_count.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_generic/rtl/prim_generic_clock_mux2.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_generic/rtl/prim_generic_pad_wrapper.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_lfsr.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_sec_anchor_buf.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_sec_anchor_flop.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_sha2_pad.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_sha2.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_sha2_32.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_sparse_fsm_flop.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_util_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_xilinx/rtl/prim_xilinx_pad_wrapper.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_xilinx_ultrascale/rtl/prim_xilinx_ultrascale_pad_wrapper.sv
/Users/javad/dev/eval/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv
/Users/javad/dev/eval/opentitan/extra_files//prim_and2.sv
/Users/javad/dev/eval/opentitan/extra_files//prim_buf.sv
/Users/javad/dev/eval/opentitan/extra_files//prim_clock_mux2.sv
/Users/javad/dev/eval/opentitan/extra_files//prim_flop.sv
/Users/javad/dev/eval/opentitan/extra_files//prim_pad_wrapper.sv
/Users/javad/dev/eval/opentitan/extra_files//prim_xnor2.sv
/Users/javad/dev/eval/opentitan/extra_files//prim_xor2.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_generic/rtl/prim_generic_flop_en.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_onehot_check.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_trivium_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_trivium.sv
/Users/javad/dev/eval/opentitan/extra_files//prim_flop_en.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_blanker.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_double_lfsr.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_generic/rtl/prim_generic_clock_inv.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim_generic/rtl/prim_generic_flop_2sync.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi4_sender.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi4_sync.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi4_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi8_sender.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi8_sync.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi8_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi12_sender.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi12_sync.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi12_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi16_sender.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi16_sync.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi16_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi20_sender.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi20_sync.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi20_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi24_sender.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi24_sync.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi24_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi28_sender.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi28_sync.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi28_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi32_sender.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi32_sync.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_mubi32_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_reg_we_check.sv
/Users/javad/dev/eval/opentitan/extra_files//prim_clock_inv.sv
/Users/javad/dev/eval/opentitan/extra_files//prim_flop_2sync.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_subreg_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_reg_cdc.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_reg_cdc_arb.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_subreg.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_subreg_arb.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_subreg_ext.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_subreg_shadow.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/tlul_pkg.sv
/Users/javad/dev/eval/opentitan/extra_files/aes_csr_assert_fpv.sv
/Users/javad/dev/eval/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_reg_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/tlul_data_integ_enc.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/tlul_data_integ_dec.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/tlul_cmd_intg_gen.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/tlul_rsp_intg_chk.sv
/Users/javad/dev/eval/opentitan/hw/ip/csrng/rtl/csrng_reg_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/csrng/rtl/csrng_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_diff_decode.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_fifo_async_sram_adapter.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_fifo_async_simple.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_fifo_async.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_fifo_sync.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_fifo_sync_cnt.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_lc_sync.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_rst_sync.sv
/Users/javad/dev/eval/opentitan/hw/ip/edn/rtl/edn_reg_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/edn/rtl/edn_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_alert_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_alert_receiver.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_alert_sender.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_esc_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_esc_receiver.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_esc_sender.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/tlul_fifo_sync.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/tlul_fifo_async.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/tlul_assert.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/tlul_err.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/tlul_assert_multiple.sv
/Users/javad/dev/eval/opentitan/hw/ip/keymgr/rtl/keymgr_reg_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/keymgr/rtl/keymgr_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_clock_gating_sync.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_sram_arbiter.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_slicer.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_sync_reqack.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_sync_reqack_data.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_sync_slow_fast.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_keccak.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_packer.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_packer_fifo.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_gate_gen.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_pulse_sync.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_filter.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_filter_ctr.sv
/Users/javad/dev/eval/opentitan/hw/ip/prim/rtl/prim_intr_hw.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/tlul_adapter_reg.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/tlul_sram_byte.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/tlul_adapter_sram.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/tlul_lc_gate.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/tlul_err_resp.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/tlul_socket_1n.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/tlul_socket_m1.sv
/Users/javad/dev/eval/opentitan/hw/ip/tlul/rtl/sram2tlul.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_reg_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_reg_top.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_ctrl_reg_shadowed.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_core.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_ctr.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_ctr_fsm.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_ctr_fsm_p.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_ctr_fsm_n.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_control.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_control_fsm.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_control_fsm_p.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_control_fsm_n.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_reg_status.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_sel_buf_chk.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_cipher_core.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_cipher_control.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_cipher_control_fsm.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_cipher_control_fsm_p.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_cipher_control_fsm_n.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_sub_bytes.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_sbox.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_sbox_lut.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_sbox_canright_pkg.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_sbox_canright.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_sbox_canright_masked_noreuse.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_sbox_canright_masked.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_sbox_dom.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_shift_rows.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_mix_columns.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_mix_single_column.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_key_expand.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_prng_clearing.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes_prng_masking.sv
/Users/javad/dev/eval/opentitan/hw/ip/aes/rtl/aes.sv
